image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\skycoin\skycoin

environment:
  GOPATH: c:\gopath
  GOX_OUTPUT: .gox_output

cache:
  - 'electron\node_modules'
  - '%LOCALAPPDATA%\Yarn'
  - '%USERPROFILE%\.electron'

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/mitchellh/gox
  - ps: Install-Product node 8 x64

build_script:
  - cd electron
  - yarn
  - ps: bash ./build.sh 'windows/amd64'

test: off

deploy:
  release: skycoin-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 5dGq3YJsuBBFtqRfgqTryWwa1fasgKWTgqiurJsY1lEtoqzrhdY3GygjpPiwiy9R
  artifact: ./release/*            # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: rl                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
