image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\iketheadore\skycoin

environment:
  GOPATH: c:\gopath

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - cd electron
  - npm run dist-win64

test: off