image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\iketheadore\skycoin

environment:
  GOPATH: c:\gopath
  GOX_OUTPUT: .gox_output

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - ps: Install-Product node 8 x64
  - ps: bash ./build.sh windows/amd64

build_script:
  - cd electron
  - npm install
  - build.sh 'windows/amd64'

test: off