name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Set up node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 10.16.3

    - name: Install gox
      run: GO111MODULE=off go get github.com/mitchellh/gox

    - name: Test
      env:
        TEST_SUIT: units
      run: ./ci-scripts/lint-and-test.sh
  
  integration_tests:
    name: IntegrationTest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Set up node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 10.16.3

    - name: Install gox
      run: GO111MODULE=off go get github.com/mitchellh/gox
      
    - name: Test
      env:
        TEST_SUIT: integrations
      run: ./ci-scripts/lint-and-test.sh
#       uses: gabrielbb/xvfb-action@v1
#       with:
#         run: ./ci-scripts/lint-and-test.sh
    
